apiVersion: v1
kind: Service
metadata:
  name: product-composite
spec:
  selector:
    app: product-composite
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 4004
      name: http-mgm
      targetPort: 4004
