apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-composite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-composite
  template:
    metadata:
      labels:
        app: product-composite
    spec:
      containers:
        - name: comp
          image: edjaz/product-composite/service
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,kubernetes"
            - name: SPRING_CONFIG_LOCATION
              value: file:/config-repo/application.yml,file:/config-repo/product-composite.yml
          envFrom:
            - secretRef:
                name: rabbitmq-credentials
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-repo-volume
              mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo-product-composite
---
apiVersion: v1
kind: Service
metadata:
  name: product-composite
spec:
  selector:
    app: product-composite
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 4004
      name: http-mgm
      targetPort: 4004