apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge-ngrok
  annotations:
    certmanager.k8s.io/issuer: "letsencrypt-issuer-prod"
spec:
  tls:
    - hosts:
        - xxxxxx.ngrok.io
      secretName: tls-ngrok-letsencrypt-certificate
  rules:
    - host: xxxxxx.ngrok.io
      http:
        paths:
          - path: /oauth
            backend:
              serviceName: auth-server
              servicePort: 9999
          - path: /product-composite
            backend:
              serviceName: product-composite
              servicePort: 8080
          - path: /actuator/health
            backend:
              serviceName: product-composite
              servicePort: 8080